README.rst
Testing making/using branches by editing the readme file.
=> listing myself as a collaborator in the readme file

course/templates/problem_set.html
=> Renamed event column in problem set to Type

canvas/static/canvas/css/course.css, canvas/templates/canvas/course_events_snippet.html, canvas/templates/canvas/course_tokens_snippet.html, static/css/main.css
- Rounding the + and - buttons, and editing the styling on the input field
- Fixing the colours of some buttons in the Events tab on the Course page
- Removing input spinners on firefox
=> Fix course page

course/templates/base_question_view.html, course/templates/problem_set.html
- Moving "Status" and "Num Attempts" columns from problem set view into question view
=> Fix problem set

api/serializers.py, api/urls.py, api/views.py, utils/category_api.py
- Implementing API to provide QuestionCategories for use in the Agular topics page
=> Category api

course/views/java.py, course/views/parsons.py
=> CG-83: updated feedback text to student after question submission

canvas/models.py, canvas/templates/canvas/course_events_snippet.html, canvas/templatetags/canvas.py, course/forms/forms.py
Instructor View:
Student View:
=> CG-87: updated text for open event button

course/models/models.py, course/tests.py
Exam questions have 10 attempts
Assignment and practice questions have 100 attempts
=> updated number of attempts for questions

canvas/models.py, canvas/templates/canvas/problem_set_snippet.html, canvas/templatetags/canvas.py
In the list of all questions for an event, remove num attempts and change status to submitted/not submitted for EXAM questions
Rebased PR of #98
=> Updated num attempts and status columns for event questions

canvas/forms/forms.py, canvas/templates/canvas/event_create.html, canvas/views/views.py
=> Updated event form styling and added type field

course/models/models.py, course/templates/base_question_view.html, course/templates/code_submission_detail.html, course/templates/past_submissions_snippet.html
=> Added tokens received to submission feedback and past submissions table

canvas/models.py, course/models/models.py, course/templates/base_question_view.html, course/templates/parsons_question.html
- In Question Summary, change "Num Attempts" to "Num Attempts Used X out X"
- Change "My Answer" to "Possible Answers" after an event is closed for MC and Checkbox questions
- For Parsons questions, change "Your Solution" to "My Solution"
Closes #111
=> updated text throughout question submission

canvas/models.py, course/models/models.py, course/templates/base_question_view.html
=> hide submit button when event is closed

course/models/models.py, course/templatetags/course.py
Fixed `Server 500` error when trying to open a non-exam event
Closes #116
=> Opening event bug

course/models/models.py, course/templates/java_question.html, course/templates/multiple_choice_question.html, course/templates/parsons_question.html, course/templatetags/course.py
Hide submit button on templates for all questions if the event is closed
=> Hide submit btn

api/serializers.py, api/urls.py, api/views.py
Added API support for the FAQ component. Used to send FAQ model data to Angular.
=> Implemented FAQ API

api/views/course.py
Minor comments explaining the course registration API
=> Course Registration API Docs

api/views/user_stats.py
- Users can now only access their own stats.
- Closes #166
=> Update User Stats Permissions

api/views/java_question.py, api/views/multiple_choice_question.py, api/views/parsons_question.py
=> Added functionality to auto-assign author on question create

accounts/models.py, api/views/admin.py, course/models/models.py, course/utils/utils.py
Without changing the functionality, this should refactor success rate calculations to one single function in `utils.py`. 
closes #171
=> Refactor success rate

api/views/submission.py
=> Support Ordering of Question Submissions

api/serializers/question.py
=> Add is_author field to Questions

api/permissions.py, api/views/question.py, api/views/user_consent.py
=> Update User Consent Permission

course/views/multiple_choice.py, course/views/parsons.py
=> Removed limitation for duplicate submission for Admins/Teachers

api/views/question.py
This PR adds the backend functionality for the frontend upload/download feature.
closes #195
=> Added django action for custom serializing all questions ready for export

api/views/uqj.py
Changed `question__event` to `question_event`
=> Changed UQJ filters to match ESLint naming conventions

api/error_messages/__init__.py, api/error_messages/additional_file_name.py, api/error_messages/answer.py, api/error_messages/category.py, api/error_messages/course.py, api/error_messages/difficulty.py, api/error_messages/event.py, api/error_messages/input_file_names.py, api/error_messages/junit_template.py, api/error_messages/lines.py, api/error_messages/max_submission_allowed.py, api/error_messages/question.py, api/error_messages/schema.py, api/error_messages/submission.py, api/error_messages/text.py, api/error_messages/title.py, api/error_messages/visible_distractor_count.py, api/serializers/java_question.py, api/serializers/multiple_choice_question.py, api/serializers/parsons_question.py, api/views/schema.py, api/views/submission.py, course/models/models.py
=> Add Error Message Classes

api/serializers/java_question.py, api/serializers/multiple_choice_question.py, api/serializers/parsons_question.py
=> Fixes Bug with Accidental Expecting Integer in Event Field

course/utils/variables.py
=> Add more names to variables schema

api/views/action.py
=> User Actions

api/serializers/java_question.py, course/models/models.py
=> Added functionality to retrieve status message from API

api/views/change_password.py, api/views/reset_password.py, api/views/update_profile.py, api/views/user_consent.py, general/models/action.py, general/services/action.py, general/tests.py
=> Account Actions

api/views/admin.py
Changes:
- Add service to view courses for the admin dashboard
Issues:
Closes: #262
=> Add admin service to view course data

canvas/models.py
=> Remove get_object_or_404s from permissions

api/views/user_consent.py
=> Save User's Name they Input in the consent form

api/serializers/uqj.py, course/models/models.py
=> Remove Status Class

course/models/models.py
=> Fix UQJ Status in the Backend

api/serializers/java_question.py, api/serializers/multiple_choice_question.py, api/serializers/parsons_question.py, course/models/models.py
=> Add submitter to submission list as a property

api/views/team.py, canvas/models/models.py, canvas/services/team.py
=> modify create-and-join-team

api/serializers/canvas_course_registration.py, api/views/canvas_course_registration.py, canvas/models/models.py
=> Token allocation for events and practice questions

api/views/course.py, api/views/event.py
=> change leader-board APIs for logging

api/serializers/course.py, canvas/models/models.py
closes #343 
Please merge this PR before the next release for the new leader board with challenges
=> Remove course leader-board proptery

api/views/event.py, course/services/question.py
=> Add event limits api

canvas/services/event.py, canvas/services/goal.py, course/models/models.py
=> Numbering challenge question names

canvas/models/models.py, canvas/services/goal.py
=> Recalcuate leaderboard tokens

README.rst, canvas/services/goal.py, course/utils/junit_xml.py
=> Edit python version in readme

api/views/course.py, api/views/event.py
=> Display students only on leaderboards

api/views/survey.py
Currently, there is no survey we are running, so the code was changed so that the server responds that there is no survey to complete.
=> Removed Survey Check

canvas/services/event.py
this is the first of a pair of prs, the second will be on the front end to actually use this new addition once this gets approved
=> add question text to event stats

api/views/course.py
Updated the grade book API to use the name field that is now mandatory and to return scores for students who have not attempted the question yet.
=> Update Gradebook API

api/error_messages/token_use.py, api/views/course.py
- updated the `my-grades` API with the same changes that the `grade-book` API received
=> Update `my-grades` API
